-- TutorPro English — lesson recording storage
-- Run this whole file in the Supabase SQL editor. Safe to run more than once.
--
-- Creates a PRIVATE bucket for classroom recordings. Files are never public;
-- the app reads them through short-lived signed URLs only.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'classroom-recordings',
  'classroom-recordings',
  false,
  1073741824, -- 1 GB per recording
  ARRAY[
    'video/webm',
    'video/mp4',
    'audio/webm',
    'application/octet-stream'
  ]
) ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 1073741824,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Only signed-in users may upload a recording (the teacher running the class).
DROP POLICY IF EXISTS "Classroom recordings upload" ON storage.objects;
CREATE POLICY "Classroom recordings upload"
  ON storage.objects FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'classroom-recordings');

-- Reading is still gated by signed URLs generated by the app.
DROP POLICY IF EXISTS "Classroom recordings read" ON storage.objects;
CREATE POLICY "Classroom recordings read"
  ON storage.objects FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'classroom-recordings');

DROP POLICY IF EXISTS "Classroom recordings update" ON storage.objects;
CREATE POLICY "Classroom recordings update"
  ON storage.objects FOR UPDATE
  TO anon, authenticated
  USING (bucket_id = 'classroom-recordings')
  WITH CHECK (bucket_id = 'classroom-recordings');

DROP POLICY IF EXISTS "Classroom recordings delete" ON storage.objects;
CREATE POLICY "Classroom recordings delete"
  ON storage.objects FOR DELETE
  TO anon, authenticated
  USING (bucket_id = 'classroom-recordings');

SELECT 'TutorPro classroom-recordings bucket ready (private, 1 GB limit)' AS result;
