/**
 * Booking emails, sent from this repository instead of from Supabase.
 *
 * WHY THIS EXISTS
 * ---------------
 * The wording of every booking email used to live only in a Supabase Edge
 * Function. Pushing a fix to this website did not change it: the function
 * had to be redeployed by hand in the Supabase dashboard, and until someone
 * did, parents kept receiving the old template.
 *
 * That is exactly what happened. The deployed function was still the
 * original bilingual one, which hardcodes Chinese next to the English on
 * every line:
 *
 *     <p>${label.en} · ${label.zh}</p>
 *     <h3 style="color:#7048df">${label.zh}</h3>
 *     ...附件中的日历事件将在上课前30分钟和10分钟提醒您。
 *
 * No change to the website could affect that, because the Chinese is inside
 * the deployed function, not in anything the website sends it. Confirmed by
 * pinging the live function with a real session: it answered
 * `400 Invalid booking notification request`, which only the old version
 * does.
 *
 * So the email moved here. This route deploys with every push, which means
 * the wording can be fixed the same way everything else on the site is.
 *
 * WHAT IT NEEDS
 * -------------
 * RESEND_API_KEY as an environment variable in Vercel. Until that is set,
 * this route answers 501 and the browser quietly falls back to the Supabase
 * function, so nothing breaks in the meantime.
 *
 * The copy itself is generated by api/_bookingEmail.js, which is a direct
 * port of supabase/functions/booking-notification/index.ts. One language
 * per recipient, chosen from their own profile — never two languages in one
 * email. scripts/test-booking-email-language.mjs checks the two stay in
 * step.
 */
import { getSupabaseAdmin } from '../_paypal.js'
import { sendError, sendJson } from '../_paypal.js'
import { EMAIL_TEMPLATE_VERSION, buildEmail, createCalendar, languageForProfile, timeZoneForProfile } from '../_bookingEmail.js'

const EVENTS = new Set(['requested', 'confirmed', 'cancelled', 'restored', 'updated'])
const FROM = process.env.NOTIFICATION_FROM_EMAIL || 'TutorPro English <notifications@tutorpro.site>'
const REPLY_TO = process.env.NOTIFICATION_REPLY_TO || 'sejongenglish@yahoo.com'

export default async function handler(req, res) {
  if (req.method !== 'POST') return sendError(res, 405, 'Method not allowed.')

  const resendKey = process.env.RESEND_API_KEY
  const body = req.body || {}

  /* A health check the admin dashboard can call without sending anything.
     It reports enough to tell the three failure modes apart - key missing,
     key present but not a Resend key, and deployment not rebuilt since the
     variable was added - WITHOUT ever echoing the key itself. */
  if (body.ping) {
    return sendJson(res, 200, {
      version: EMAIL_TEMPLATE_VERSION,
      sender: 'vercel',
      configured: Boolean(resendKey),
      keyLooksRight: typeof resendKey === 'string' && resendKey.startsWith('re_'),
      // Which commit this deployment was built from. If this does not move
      // after a redeploy, the redeploy did not happen.
      builtFrom: (process.env.VERCEL_GIT_COMMIT_SHA || '').slice(0, 7),
      builtAt: process.env.VERCEL_DEPLOYMENT_ID ? 'vercel' : 'unknown',
      // Proof the runtime can see project variables at all. Names only.
      sampleVarsPresent: ['RESEND_API_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'PAYPAL_CLIENT_ID']
        .filter((name) => Boolean(process.env[name])),
    })
  }

  // Not configured yet: say so plainly so the browser can fall back.
  if (!resendKey) return sendError(res, 501, 'RESEND_API_KEY is not set in Vercel, so this route cannot send email yet.')

  const { bookingId, event = 'updated' } = body
  if (!bookingId || !EVENTS.has(event)) return sendError(res, 400, 'Invalid booking notification request.')

  const header = req.headers?.authorization || ''
  const token = header.startsWith('Bearer ') ? header.slice(7) : ''
  if (!token) return sendError(res, 401, 'Please log in again.')

  let supabase
  let user
  try {
    supabase = getSupabaseAdmin()
    const { data, error } = await supabase.auth.getUser(token)
    if (error || !data?.user?.id) throw new Error('Your session could not be verified.')
    user = data.user
  } catch (authError) {
    return sendError(res, 401, authError.message)
  }

  try {
    const { data: row, error: bookingError } = await supabase.from('bookings').select('*').eq('id', bookingId).single()
    if (bookingError || !row) throw new Error('Booking could not be loaded.')
    const booking = { ...(row.booking_data || {}), id: row.id, studentId: row.student_id, teacherId: row.teacher_id, status: row.status }

    /* Only the two people in the lesson, or an administrator. */
    const { data: adminMember } = await supabase.from('admin_members').select('user_id').eq('user_id', user.id).maybeSingle()
    if (user.id !== booking.studentId && user.id !== booking.teacherId && !adminMember) {
      return sendError(res, 403, 'Not authorized for this booking.')
    }

    const { data: profiles } = await supabase
      .from('profiles').select('id,email,login_id,parent_name,full_name,profile_data')
      .in('id', [booking.studentId, booking.teacherId].filter(Boolean))
    const student = profiles?.find((p) => p.id === booking.studentId)
    const teacher = profiles?.find((p) => p.id === booking.teacherId)
    const learner = student?.profile_data?.children?.find((c) => c.id === booking.learnerId) || student?.profile_data?.child
    const studentName = learner?.name || booking.learnerName || 'Student'
    const teacherName = teacher?.full_name || teacher?.profile_data?.fullName || booking.teacherName || 'TutorPro Teacher'

    /* Lesson times are stored in Manila time. */
    const start = new Date(`${booking.date}T${booking.time}:00+08:00`)

    const recipients = [student, teacher]
      .filter(Boolean)
      .map((profile) => ({
        email: profile.email || profile.login_id,
        language: languageForProfile(profile),
        timeZone: timeZoneForProfile(profile),
      }))
      .filter((r) => typeof r.email === 'string' && r.email.includes('@'))

    if (!recipients.length) return sendJson(res, 200, { delivered: false, reason: 'No participant emails' })

    /* buildEmail returns only the subject and body; the .ics is built once
       and attached to both copies. Forgetting this silently dropped the
       calendar invitation, which is half the value of the email. */
    const calendar = createCalendar(booking, studentName, teacherName)

    const sent = []
    const failed = []
    for (const recipient of recipients) {
      const mail = buildEmail({
        language: recipient.language,
        timeZone: recipient.timeZone,
        event,
        start,
        studentName,
        teacherName,
        focus: booking.focus || 'English lesson',
        duration: Number(booking.duration || 25),
      })
      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { Authorization: `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: FROM,
          to: [recipient.email],
          // tutorpro.site has no MX record, so a reply to notifications@
          // would vanish. Point replies at a mailbox that exists.
          reply_to: REPLY_TO,
          subject: mail.subject,
          html: mail.html,
          attachments: calendar ? [{ filename: `TutorPro-English-${booking.date}.ics`, content: Buffer.from(calendar, 'utf8').toString('base64') }] : undefined,
        }),
      })
      if (response.ok) sent.push({ email: recipient.email, language: recipient.language })
      else failed.push({ email: recipient.email, why: (await response.text()).slice(0, 200) })
    }

    return sendJson(res, 200, { delivered: sent.length > 0, sender: 'vercel', version: EMAIL_TEMPLATE_VERSION, sent, failed })
  } catch (error) {
    return sendError(res, 400, error.message)
  }
}
