import QRCode from 'qrcode'

/**
 * Local QR code generation for referral links.
 *
 * WHY THIS EXISTS
 * ---------------
 * Referral QR codes were generated by api.qrserver.com, an external service that
 * is unreliable or blocked in mainland China. Chinese parents saw a broken image
 * where the referral QR should be — and QR codes are the primary sharing method
 * on WeChat, so this mattered more in China than anywhere else.
 *
 * Generating locally means the QR:
 *   - works in mainland China with no external request
 *   - works offline and cannot be rate-limited
 *   - is identical for the same input, so a parent's QR never changes
 *   - costs nothing
 *
 * Uses the `qrcode` package rather than a hand-written encoder: QR encoding has
 * many subtle spec details (block interleaving, format bit ordering, remainder
 * bits) where a small mistake produces a code that looks right but will not scan.
 */

const DEFAULTS = {
  errorCorrectionLevel: 'M',
  margin: 4,
  color: { dark: '#160b2dff', light: '#ffffffff' },
}

/**
 * Render a QR code as an inline SVG data URI. Synchronous and safe to call
 * during render — no network, no async state needed.
 *
 * @param {string} text  Content to encode, normally a referral URL.
 * @param {object} opts  { size, margin, dark, light }
 * @returns {string} data:image/svg+xml URI, or '' if encoding fails.
 */
export function qrDataUri(text, opts = {}) {
  const value = String(text || '').trim()
  if (!value) return ''
  const { size = 240, margin = DEFAULTS.margin, dark = '#160b2d', light = '#ffffff' } = opts
  try {
    // toString with type 'svg' is synchronous when no callback is supplied.
    let svg = ''
    QRCode.toString(value, {
      type: 'svg',
      errorCorrectionLevel: DEFAULTS.errorCorrectionLevel,
      margin,
      width: size,
      color: { dark, light },
    }, (error, result) => {
      if (!error && result) svg = result
    })
    if (!svg) return ''
    return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`
  } catch {
    return ''
  }
}

/** Async PNG data URL, used where a raster image is needed (poster download). */
export async function qrPngDataUrl(text, opts = {}) {
  const value = String(text || '').trim()
  if (!value) return ''
  const { size = 480, margin = DEFAULTS.margin, dark = '#160b2d', light = '#ffffff' } = opts
  try {
    return await QRCode.toDataURL(value, {
      errorCorrectionLevel: DEFAULTS.errorCorrectionLevel,
      margin,
      width: size,
      color: { dark, light },
    })
  } catch {
    return ''
  }
}
